### ISSUE TITLE
java.net.UnknownHostException: graph.facebook.com

### ISSUE THREAD

**Issue by vshbhan** [arpitaggarwal/spring-social#3]
Hi arpit,
      I changed all the keys accordingly and tried to login with facebook. Login succeeds but after that above mentioned error comes up.

**Comment by arpitaggarwal** [comment]
Seems there is a proxy or firewall issue preventing you from seeing `graph.facebook.com`. Try point your browser at `http://graph.facebook.com`, you should at least get back the following JSON:

```
{
   "error": {
      "message": "Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100,
      "fbtrace_id": "CoNlxffLL+/"
   }
}
```

**Comment by vshbhan** [comment]
Im am getting back the specified json object. I even made proxy settings in the controller but the issue is still the same

**Comment by arpitaggarwal** [comment]
Seems like you are facing the same problem as OP faced here - http://stackoverflow.com/questions/34088124/unknownhostexception-graph-facebook-com

**Comment by vshbhan** [comment]
I was making mistake while specifying proxy setting. Its working now. Thanks :)
